- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> CLOUD-468 upgrade gradle to 2.3

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClient.groovy
> CLOUD-868: ability to get ambari requests with specific statuses

- src/main/groovy/com/sequenceiq/ambari/client/services/BlueprintService.groovy
- src/test/groovy/com/sequenceiq/ambari/client/AmbariBlueprintsTest.groovy
- src/test/resources/hdp-blueprint-inner-properties-result.json
- src/test/resources/hdp-blueprint-inner-properties.json
- src/test/resources/hdp-blueprint-inner-properties2-result.json
- src/test/resources/hdp-blueprint-inner-properties2.json
@keyki this pr fixing the property addition problem
> CLOUD-41683 fixed property redefinition

- src/main/groovy/com/sequenceiq/ambari/client/services/KerberosService.groovy
- src/test/groovy/com/sequenceiq/ambari/client/AmbariKerberosTest.groovy
@schfeca75 I found a small plz review
> CLOUD-43362 Fix kerberos service generateKeyTabs()

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClient.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/ViewService.groovy
> CLOUD-45463 create default views

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClient.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CLOUD-49845 Send rack infor to Ambari

- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CLOUD-51494 Check ambari version before sending rack_info

- src/main/groovy/com/sequenceiq/ambari/client/services/KerberosService.groovy
- src/test/groovy/com/sequenceiq/ambari/client/AmbariKerberosTest.groovy
- src/test/resources/multi-node-hdfs-yarn-default-kerb_descriptor.json
- src/test/resources/multi-node-hdfs-yarn-default-kerb_descriptor_fixed.json
> CLOUD-50248 if security block is defined only change the type

- src/main/resources/blueprints/single-node-hdfs-yarn
> CLOUD-53040 Fix single-node-hfs-yarn blueprint json

- src/main/groovy/com/sequenceiq/ambari/client/services/HBaseService.groovy
> CLOUD-53068 check HBASE RS state

- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CLOUD-58091 SmartSense data caputre could be triggered

- src/main/groovy/com/sequenceiq/ambari/client/services/BlueprintService.groovy
> CLOUD-58628 addHostsWithBlueprint() return operation id

- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CLOUD-58628 'default' config params changed to 'Default'

- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CLOUD-56731 ability to specify default password

- src/main/groovy/com/sequenceiq/ambari/client/services/ViewService.groovy
> CLOUD-63600 added view info

- src/main/groovy/com/sequenceiq/ambari/client/services/ViewService.groovy
> CLOUD-63600 use latest version

- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CLOUD-64325 OpenStack topology mapping error

- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
@keyki lets talk this tomorrow
> CLOUD-65838 added config query by config id

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClient.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/GroupService.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/UserService.groovy
* Allow getting user data, granting/revoking admin privilege,
activating/inactivating users.
* Allow creating, getting, and deleting groups, adding and removing members.
* Changed unused `admin` parameter of `UserService.changePassword`
to be optional.
> Expanded user service, added group service

- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CLOUD-82601 ambari request progress retrieval fix

- src/main/groovy/com/sequenceiq/ambari/client/services/BlueprintService.groovy
> CLOUD-92658 Exisitng config params won't be overriden in blueprint

- src/main/groovy/com/sequenceiq/ambari/client/services/BlueprintService.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/KerberosService.groovy
- src/test/groovy/com/sequenceiq/ambari/client/AmbariBlueprintsTest.groovy
- src/test/groovy/com/sequenceiq/ambari/client/AmbariKerberosTest.groovy
- src/test/resources/hdp-streaming-forced-modified.json
- src/test/resources/multi-node-hdfs-yarn-default-kerb_descriptor_forced_fixed.json
- src/test/resources/multi-node-hdfs-yarn-forced-config.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-config.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-forced-config.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-master-slave-config.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-master-slave-forced-config.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-with-config-result.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-with-forced-config-result.json
- src/test/resources/multi-node-hdfs-yarn-heterogen-with-multi-config.json
- src/test/resources/multi-node-hdfs-yarn-kerb-forced.json
- src/test/resources/multi-node-hdfs-yarn-kerb.json
> CLOUD-92658 blueprint config overwriting is controlled by the forced parameter

- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CLOUD-93033 extend ambariclient with getVersionDefinitions method

- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
added method to create cluster from template
> BUG-100311#

- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> BUG-116111 get config params by service types

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClientUtils.groovy
- src/main/groovy/com/sequenceiq/ambari/client/model/HostComponentStatuses.java
- src/main/groovy/com/sequenceiq/ambari/client/model/HostStatus.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CB-3662 Extend client with multiple hosts status retrive and multiple hosts delete calls

- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CB-3662 log delete hosts ambari response

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClient.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CB-3662 change multiple hosts delete calls to use body instead of query params

- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CB-3662 fix logging

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClientUtils.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/ServiceAndHostService.groovy
> CB-3662 remove hosts filtering param from get host statuses queries

- src/main/groovy/com/sequenceiq/ambari/client/AmbariClientUtils.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/AlertService.groovy
- src/main/groovy/com/sequenceiq/ambari/client/services/ClusterService.groovy
> CB-3586 new call for specific alert retrival
